version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - service-net
    
  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
    environment:
      - STAN_CLUSTER_ID=order-cluster
    networks:
      - service-net

  service:
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
    build:
      context: ./service
    depends_on:
      - postgres
      - nats
    networks:
      - service-net
    ports:
      - "8080:8080"

  sender:
    environment:
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
    build:
      context: ./sender
    depends_on:
      - nats
    networks:
      - service-net
    ports:
      - "8081:8081"

networks:
  service-net:

volumes:
  postgres_data:
